### ISSUE TITLE
Attribute error of preprocess

### ISSUE THREAD

**Issue by ykyohei** [simonsobs/sotodlib#1560]
I find this error in running multilayer preprocess for isov4 archive now.
This is introduced in #1556, by this line https://github.com/simonsobs/sotodlib/blob/97af2928d3294f44dfb2e4219a8caaae371b8c6a/sotodlib/preprocess/processes.py#L2914

```
    aman = preprocess_util.multilayer_load_and_preprocess(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyoheiy/repos/sotodlib/sotodlib/preprocess/preprocess_util.py", line 614, in multilayer_load_and_preprocess
    aman_cfgs_ref = get_pcfg_check_aman(pipe_init)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyoheiy/repos/sotodlib/sotodlib/preprocess/preprocess_util.py", line 1486, in get_pcfg_check_aman
    pcfg_ref[f'{i}_{pp.name}'].wrap(memb[0], memb[1])
  File "/home/kyoheiy/repos/sotodlib/sotodlib/core/axisman.py", line 689, in wrap
    assign = [None for s in data.shape]
                            ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'shape'
```
